# Copyright 2025 Bret Jordan, All rights reserved.

# ------------------------------------------------------------
# Remove Cloud-Init
# ------------------------------------------------------------
# Remove the cloud-init packages and all of its files after first boot. One
# could just disable cloud-init to prevent it from starting, but that can leave
# senstive information on the system that is world readable. In my use case I
# have no additional need for cloud-init, so I am just removing it and all of
# its files.

- name: Remove and pruge cloud init packages
  ansible.builtin.apt:
    name: cloud-init
    state: absent
    purge: true

- name: Remove /etc/cloud
  ansible.builtin.file:
    path: /etc/cloud
    state: absent

- name: Remove /var/lib/cloud
  ansible.builtin.file:
    path: /var/lib/cloud
    state: absent

- name: Remove /boot/firmware/user-data
  ansible.builtin.file:
    path: /boot/firmware/user-data
    state: absent

- name: Remove /boot/firmware/meta-data
  ansible.builtin.file:
    path: /boot/firmware/meta-data
    state: absent

- name: Remove /boot/firmware/network-config
  ansible.builtin.file:
    path: /boot/firmware/network-config
    state: absent
