---

# Copyright 2025 Bret Jordan, All rights reserved.

# ------------------------------------------------------------
# Reboot all nodes
# ------------------------------------------------------------
# Shell: ansible all -m reboot -b

- hosts: nodes
  gather_facts: false
  become: true
  tasks:

  - name: reboot all nodes
    ansible.builtin.reboot:
