---

# Copyright 2025 Bret Jordan, All rights reserved.

# A simple playbook to bootstrap all of the nodes. 

- hosts: nodes
  become: true
  tasks:

# ------------------------------------------------------------
# Secure SSH access
# ------------------------------------------------------------
  - name: Remove root SSH access
    tags: always
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: "^PermitRootLogin" 
      line: "PermitRootLogin no" 
      state: present

  - name: Remove password SSH access
    tags: always
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: "^PasswordAuthentication" 
      line: "PasswordAuthentication no" 
      state: present
