---

# Copyright 2025 Bret Jordan, All rights reserved.

# ------------------------------------------------------------
# Shutdown all nodes and TuringPi boards
# ------------------------------------------------------------

- hosts: nodes
  become: true
  gather_facts: true
  gather_timeout: 5
  any_errors_fatal: false
  ignore_unreachable: true
  tasks:

  - name: shutdown each node in the cluster
    ansible.builtin.command: 
      cmd: /sbin/shutdown --poweroff now

  - name: wait for the node to go down
    ansible.builtin.wait_for:
      host: "{{ ansible_host }}"
      port: 22 
      state: stopped
      timeout: 5
    delegate_to: localhost
